### PR TITLE
fix: Accordion menu not showing new result when children changed

### LINKED ISSUE #76: Accordion menu not show active entry when changed

### PR DESCRIPTION
**Pull request by memoyil**
Fixes #76

### CODE REVIEW

File: packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx [hunk 1]
```diff
@@ -69,7 +69,21 @@ const Accordion: React.FC<Props> = ({
...
+          const nextMenuEntry = nextChildren[index] as ReactElement;
+          return (
+            prevMenuEntry.props.isActive === nextMenuEntry.props.isActive &&
+            prevMenuEntry.props.isPushed === nextMenuEntry.props.isPushed
+          );
+        })
+      : true;
+
+  return prev.isPushed === next.isPushed && prev.isActive === next.isActive && isChildrenSame;
+});
```
Comment (hachiojidev) [inline packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx:89]: I don't think this is the right solution for this problem. It seems that we are trying to solve a problem that doesn't exist. In my opinion we should remove `React.memo`. The Accordion is not a complex and re-renders will not cause a performance issue. React is pretty good at optimizing.

@RabbitDoge What do you think?

**Review by hachiojidev — CHANGES_REQUESTED** [review]

File: packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx (hunk 1 above)
Comment (RabbitDoge) [reply packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx:89]: I would rather remove the memo instead of adding some complex and hacky code , for sure. This logic could as well remove the small gain we have from the memo

Comment (hachiojidev) [reply packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx:89]: @memoyil Can you revert this change and simply remove the memo?

**Review by hachiojidev — CHANGES_REQUESTED** [review]

File: packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx (hunk 1 above)
Comment (memoyil) [reply packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx]: done

**Review by hachiojidev — APPROVED** [review]
